<?php
/*
HLstatsX Community Edition - Real-time player and clan rankings and statistics
Copyleft (L) 2008-20XX Nicholas Hastings (nshastings@gmail.com)
http://www.hlxcommunity.com

HLstatsX Community Edition is a continuation of 
ELstatsNEO - Real-time player and clan rankings and statistics
Copyleft (L) 2008-20XX Malte Bayer (steam@neo-soft.org)
http://ovrsized.neo-soft.org/

ELstatsNEO is an very improved & enhanced - so called Ultra-Humongus Edition of HLstatsX
HLstatsX - Real-time player and clan rankings and statistics for Half-Life 2
http://www.hlstatsx.com/
Copyright (C) 2005-2007 Tobias Oetzel (Tobi@hlstatsx.com)

HLstatsX is an enhanced version of HLstats made by Simon Garner
HLstats - Real-time player and clan rankings and statistics for Half-Life
http://sourceforge.net/projects/hlstats/
Copyright (C) 2001  Simon Garner
            
This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

For support and installation notes visit http://www.hlxcommunity.com
*/

    if (!defined('IN_HLSTATS')) {
        die('Do not access this file directly.');
    }
	
	/*
	 * HLstatsX Page Header This file will be inserted at the top of every page
	 * generated by HLstats. This file can contain PHP code.
	 */
	 
	// hit counter
	$db->query("UPDATE hlstats_Options SET value=value+1 WHERE keyname='counter_hits';"); 
  
	// visit counter
	if (isset($_COOKIE['ELstatsNEO_Visit']) && $_COOKIE['ELstatsNEO_Visit'] == 0) {
		// kein cookie gefunden, also visitcounter erh�hen und cookie setzen
		$db->query("UPDATE hlstats_Options SET value=value+1 WHERE keyname='counter_visits';");
		@setcookie('ELstatsNEO_Visit', '1', time() + ($g_options['counter_visit_timeout'] * 60), '/');   
	}
     
	global $game,$mode;

	$iconpath = IMAGE_PATH . "/icons";
	if (file_exists($iconpath . "/" . $style)) {
			$iconpath = $iconpath . "/" . $style;
	}
	
?>
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="apple-touch-icon" sizes="76x76" href="../assets/img/apple-icon.png">
  <link rel="icon" type="image/png" href="../assets/img/favicon.png">
  <title>
  <?php
	echo $g_options['sitename']; 
	foreach ($title as $t)
	{
		echo " - $t";
	}
  ?>
  </title>
  <!--     Fonts and icons     -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet" />
  <!-- Nucleo Icons -->
  <link href="assets/css/nucleo-icons.css" rel="stylesheet" />
  <link href="assets/css/nucleo-svg.css" rel="stylesheet" />
  <!-- Font Awesome Icons -->
  <script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>
  <link href="assets/css/nucleo-svg.css" rel="stylesheet" />
  <!-- Bootstrap Icons -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css" rel="stylesheet" />
  <!-- CSS Files -->
  <link id="pagestyle" href="assets/css/argon-dashboard.css?v=2.0.4" rel="stylesheet" />
</head>

<body class="g-sidenav-show bg-gray-100">
  <div class="min-height-300 themec position-absolute w-100 bg-primary"></div>
  <aside class="sidenav bg-white navbar navbar-vertical navbar-expand-xs border-0 border-radius-xl my-3 fixed-start ms-4 " id="sidenav-main">
    <div class="sidenav-header">
      <i class="fas fa-times p-3 cursor-pointer text-secondary opacity-5 position-absolute end-0 top-0 d-none d-xl-none" aria-hidden="true" id="iconSidenav"></i>
      <a class="navbar-brand m-0" href=" <?php echo $g_options['scripturl']; ?> " target="_self">
        <img src="assets/images/logo-ct-dark.png" class="navbar-brand-img h-100" alt="main_logo">
        <span class="ms-1 font-weight-bold">HLX: CE</span>
      </a>
    </div>
    <hr class="horizontal dark mt-0">
    <div class="navbar-collapse w-auto " id="sidenav-collapse-main">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="<?php echo $g_options['scripturl'] ?>">
            <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
              <i class="bi bi-house text-primary text-sm opacity-10"></i>
            </div>
            <span class="nav-link-text ms-1">Home</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link " href="<?php echo $g_options['scripturl'] ?>?mode=search">
            <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
              <i class="bi bi-search text-warning text-sm opacity-10"></i>
            </div>
            <span class="nav-link-text ms-1">Search</span>
          </a>
        </li>
        <?php
        if ($g_options['sourcebans_address']){
        echo '<li class="nav-item">
          <a class="nav-link " href="' . $g_options['sourcebans_address'] . '">
            <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
              <i class="bi bi-hammer text-danger text-sm opacity-10"></i>
            </div>
            <span class="nav-link-text ms-1">Bans</span>
          </a>
        </li>';
        }
        if ($g_options['forum_address']){
        echo '<li class="nav-item">
          <a class="nav-link " href="' . $g_options['forum_address'] . '">
            <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
              <i class="bi bi-chat-square-quote-fill text-info text-sm opacity-10"></i>
            </div>
            <span class="nav-link-text ms-1">Forum</span>
          </a>
        </li>';
        }
        if ($g_options['discord_address']){
          echo '<li class="nav-item">
            <a class="nav-link " href="' . $g_options['discord_address'] . '">
              <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
                <i class="bi bi-discord text-primary text-sm opacity-10"></i>
              </div>
              <span class="nav-link-text ms-1">Discord</span>
            </a>
          </li>';
          }
        if ($g_options['custom_link_1']){
          $custom1 = $g_options['custom_link_1'];
          $custom1_array = explode(';', $custom1);
          echo '<li class="nav-item">
            <a class="nav-link " href="' . $custom1_array['3'] . '">
              <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
                <i class="bi ' . $custom1_array['2'] .' ' . $custom1_array['1'] . ' text-sm opacity-10"></i>
              </div>
              <span class="nav-link-text ms-1">' . $custom1_array['0'] . '</span>
            </a>
          </li>';
          }
        if ($g_options['custom_link_2']){
          $custom2 = $g_options['custom_link_2'];
          $custom2_array = explode(';', $custom2);
          echo '<li class="nav-item">
            <a class="nav-link " href="' . $custom2_array['3'] . '">
              <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
                <i class="bi ' . $custom2_array['2'] .' ' . $custom2_array['1'] . 'text-sm opacity-10"></i>
              </div>
              <span class="nav-link-text ms-1">' . $custom3_array['0'] . '</span>
            </a>
          </li>';
          }
        if ($g_options['custom_link_3']){
          $custom3 = $g_options['custom_link_3'];
          $custom3_array = explode(';', $custom3);
          echo '<li class="nav-item">
            <a class="nav-link " href="' . $custom3_array['3'] . '">
              <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
                <i class="bi ' . $custom3_array['2'] .' ' . $custom3_array['1'] . 'text-sm opacity-10"></i>
              </div>
              <span class="nav-link-text ms-1">' . $custom3_array['0'] . '</span>
            </a>
          </li>';
          }
        ?>
        <li class="nav-item">
          <a class="nav-link " href="<?php echo $g_options['scripturl'] ?>?mode=help">
            <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
              <i class="bi bi-info-lg text-success text-sm opacity-10"></i>
            </div>
            <span class="nav-link-text ms-1">Help</span>
          </a>
        </li>
        <?php
        if ($game != '') {
        echo '<li class="nav-item mt-3">
          <h6 class="ps-4 ms-2 text-uppercase text-xs font-weight-bolder opacity-6">Server Menu</h6>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="' . $g_options['scripturl'] . '?game=' . $game . '">
            <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
              <i class="bi bi-hdd-stack-fill text-dark text-sm opacity-10"></i>
            </div>
            <span class="nav-link-text ms-1">Servers</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link " href="' . $g_options['scripturl']  . '?mode=chat&amp;game=' . $game . '">
            <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
              <i class="bi bi-chat-dots-fill text-warning text-sm opacity-10"></i>
            </div>
            <span class="nav-link-text ms-1">Chat</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link " href="' . $g_options['scripturl'] . '?mode=players&amp;game=' . $game . '">
            <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
              <i class="bi bi-person-fill text-purple text-sm opacity-10"></i>
            </div>
            <span class="nav-link-text ms-1">Players</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link " href="' . $g_options['scripturl'] . '?mode=clans&amp;game=' . $game . '">
            <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
              <i class="bi bi-people-fill text-teal text-sm opacity-10"></i>
            </div>
            <span class="nav-link-text ms-1">Clans</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link " href="' . $g_options['scripturl'] . '?mode=countryclans&amp;game=' . $game . '&amp;sort=nummembers">
            <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
              <i class="bi bi-globe2 text-info text-sm opacity-10"></i>
            </div>
            <span class="nav-link-text ms-1">Countries</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link " href="' . $g_options['scripturl'] . '?mode=awards&amp;game=' . $game . '">
            <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
              <i class="bi bi-award-fill text-yellow text-sm opacity-10"></i>
            </div>
            <span class="nav-link-text ms-1">Awards</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link " href="' . $g_options['scripturl'] . '?mode=actions&amp;game=' . $game . '">
            <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
              <i class="bi bi-bullseye text-danger text-sm opacity-10"></i>
            </div>
            <span class="nav-link-text ms-1">Actions</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link " href="' . $g_options['scripturl'] . '?mode=weapons&amp;game=' . $game . '">
            <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
              <i class="bi bi-heart-arrow text-pink text-sm opacity-10"></i>
            </div>
            <span class="nav-link-text ms-1">Weapons</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link " href="' . $g_options['scripturl'] . '?mode=maps&amp;game=' . $game . '">
            <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
              <i class="bi bi-map-fill text-success text-sm opacity-10"></i>
            </div>
            <span class="nav-link-text ms-1">Maps</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link " href="' . $g_options['scripturl'] . '?mode=roles&amp;game=' . $game . '">
            <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
              <i class="bi bi-person-vcard-fill text-indigo text-sm opacity-10"></i>
            </div>
            <span class="nav-link-text ms-1">Roles</span>
          </a>
        </li>
        '; }
        ?>
      </ul>
    </div>
  </aside>
  <main class="main-content position-relative border-radius-lg ">
    <!-- Navbar -->
    <nav class="navbar navbar-main navbar-expand-lg px-0 mx-4 shadow-none border-radius-xl " id="navbarBlur" data-scroll="false">
      <div class="container-fluid py-1 px-3">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb bg-transparent mb-0 pb-0 pt-1 px-0 me-sm-6 me-5">
            <?php echo '<li class="breadcrumb-item text-sm"><a class="opacity-5 text-white" href="http://' . preg_replace('/http:\/\//', '', $g_options['siteurl']) . '">'. $g_options['sitename'] .'</a></li>';
            $i = 0;
            foreach ($location as $l => $url) {
              $url = preg_replace('/%s/', $g_options['scripturl'], $url);
              $url = preg_replace('/&/', '&amp;', $url);
              echo '<li class="breadcrumb-item text-sm text-white" aria-current="page">';
              if ($url) {
                echo '<a class="opacity-5 text-white" href="'. $url .'">'. $l .'</a></li>';
              } else {
                echo  $l .'</li>
          </ol>
          <h6 class="font-weight-bolder text-white mb-0">'. $l .'</h6>';
              }
              $i++;
            } ?>

        </nav>
        <div class="collapse navbar-collapse mt-sm-0 mt-2 me-md-0 me-sm-4" id="navbar">
          <div class="ms-md-auto pe-md-3 d-flex align-items-center">
            <div class="input-group">
              <span class="input-group-text text-body"><i class="fas fa-search" aria-hidden="true"></i></span>
              <input type="text" class="form-control" placeholder="Type here..." name="general-search" id="general-search">
            </div>
          </div>
          <ul class="navbar-nav  justify-content-end">
            <li class="nav-item d-flex align-items-center">
              <a href="<?php echo $g_options['scripturl']; ?>?mode=admin" class="nav-link text-white font-weight-bold px-0">
                <i class="bi bi-door-open-fill me-sm-1"></i>
                <span class="d-sm-inline d-none">Admin</span>
              </a>
            </li>
            <?php
            if (isset($_SESSION['loggedin'])) {
              echo '<li class="nav-item px-3 d-flex align-items-center">
              <a href="hlstats.php?logout=1" class="nav-link text-white font-weight-bold px-0">
                <i class="bi bi-door-closed-fill me-sm-1"></i>
                <span class="d-sm-inline d-none">Logout</span>
              </a>
            </li>';
            }
            ?>
            <li class="nav-item d-xl-none d-flex align-items-center">
              <a href="javascript:;" class="nav-link text-white p-0" id="iconNavbarSidenav">
                <div class="sidenav-toggler-inner">
                  <i class="sidenav-toggler-line bg-white"></i>
                  <i class="sidenav-toggler-line bg-white"></i>
                  <i class="sidenav-toggler-line bg-white"></i>
                </div>
              </a>
            </li>
            <li class="nav-item px-3 d-flex align-items-center">
              <a href="javascript:;" class="nav-link text-white p-0">
                <i class="fa fa-cog fixed-plugin-button-nav cursor-pointer"></i>
              </a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <!-- End Navbar -->